# App
spring.application.name=incident-management-api

# Database
spring.flyway.enabled=true
spring.datasource.url=jdbc:postgresql://localhost:5432/incident_platform
spring.datasource.username=app_user
spring.datasource.password=password
